### PR TITLE
Fix parse call in getRequestHandlerForRoutes

### PR DESCRIPTION
**Pull request by jth0024**

### CODE REVIEW

**Review by Arno500 — APPROVED** [review]
Fix a bug in latest Next.JS version where the query parameter object expects a "amp" entry. Needed for the latest version to work on.

**Comment by AndrewIngram** [comment]
@jth0024 can you explain what this is fixing? As an aside, we're not actually using the handler from this module because we've had to hack it up for our own purposes.

@Arno500 is that a different issue?

**Comment by Arno500** [comment]
@AndrewIngram No, because adding it fixes the issue. I don't know how the method parse works in details and why adding this true argument makes it works.

**Comment by jth0024** [comment]
@AndrewIngram Your code is using the `url` module. The `url.parse` method will ignore the querystring by default.  If you want to parse the querystring, you must provide `true` as the second argument. The query object is required in order for the page to render properly, so we do want to parse it in this case. You can find the documentation for this second parameter [here](https://www.npmjs.com/package/url#urlparseurlstr-parsequerystring-slashesdenotehost). You can also see that NextJS's own [documentation](https://nextjs.org/docs#custom-server-and-routing) shows an example where `true` is provided as the second parameter to `url.parse`.

Side note, I noticed the module isn't used, but I figured I'd provide the fix anyway in case you decided to use it later.

**Comment by AndrewIngram** [comment]
Ah, I think it hasn't been an issue for us because we don't have any pages where query string parameters end up as page params.

I've just been looking at doing a much simpler piece of middleware for express:

```javascript
import express from 'express';

export default function nextRouteMiddleware(routes, app) {
  const router = express.Router();

  routes.forEach(route => {
    router.get(route.path, (req, res) => {
      app.render(req, res, route.page, { ...route.params, ...req.params }); 
    });
  });

  return router;
}
```

(you can modify param spreading if you need query strings too)

The idea is that you use it alongside the normal Next handler:

```javascript
server.use(nextRouteMiddleware(routes, app));
server.get('*', app.getRequestHandler());
```

**Comment by AndrewIngram** [comment]
A slightly more elaborate version that takes care of query strings too:

```javascript
import express from 'express';

export default function nextRouteMiddleware(
  routes,
  app,
  options = { strict: true },
) {
  const router = express.Router(options);

  routes.forEach(route => {
    if (options.strict && route.path.endsWith('/')) {
      router.get(route.path.slice(0, -1), (req, res) =>
        res.redirect(301, route.path),
      );
    }
    router.get(route.path, (req, res) => {
      // Don't allow query strings to overwrite route params
      const filteredQuery = Object.keys(req.query).reduce((acc, key) => {
        if (!route.allKeyNames.includes(key)) {
          acc[key] = req.query[key];
        }
        return acc;
      }, {});
      app.render(req, res, route.page, {
        ...route.params,
        ...req.params,
        ...filteredQuery,
      });
    });
  });

  return router;
}
```

I'm thinking it might be better to just include something like this in the readme rather than as part of the library itself? I think there are several valid ways to hook it up to Express and I don't want to be too opinionated here.

**Comment by jth0024** [comment]
@AndrewIngram  I really like the idea of registering each route pattern individually and letting Express resolve the routes. I think that's more performant than trying to match outside of express's built-in router.  I also agree that being too opinionated can be bad. Like you said, there are a lot of valid ways to hook up to an express server. On the other hand, it's nice to have a default option for users that _just works_. So, maybe you could export an opinionated default and also document how to wire up the routing logic manually for special use cases?

**Comment by jth0024** [comment]
@AndrewIngram Also, to avoid the conflict between query params and path params, you could pass path params under a single key like this:
```
      app.render(req, res, route.page, {
         ...req.query,
        params: { ...req.params, ...route.params },
      });
```

**Pull request merged**
